name: Docs

on: [push]

jobs:
  deploy_docs:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v2

      - name: Build Docs
        uses: sersoft-gmbh/swifty-docs-action@v3.0.0
        with:
          output: docs
          targets: Motion
          enable-index-building: false
          transform-for-static-hosting: true
          hosting-base-path: Motion

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_ACCESS_TOKEN }}
          publish_dir: ./docs
